# Generated by Django 4.2.5 on 2023-11-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version_product_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='version',
            new_name='version_of_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', to_field='title'),
        ),
    ]
