# Generated by Django 4.2.5 on 2023-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_version_product_version_of_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование продукта'),
        ),
    ]
