# Generated by Django 4.2.5 on 2023-11-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', to_field='title'),
        ),
    ]
