# Generated by Django 4.2.5 on 2023-11-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_version_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='version_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product', to_field='title'),
        ),
    ]
