# Generated by Django 4.2.5 on 2023-10-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик просморов'),
        ),
    ]
